services:
  glances:
    image: nicolargo/glances:latest
    restart: always
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    ports:
      - "9011:61208"
    networks:
      - web_lapig
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 100M

  jupyterhub:
    image: lapig/geojupyterhub:v1
    container_name: jupyterhub
    hostname: jupyterhub
    ports:
      - "8000:443"
    volumes:
      - ../var/db:/srv/jupyterhub
      - ../scripts:/srv/jupyterhub/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - ../data/users.json:/srv/jupyterhub/users.json:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
   # environment:
      # - DOCKER_NETWORK_NAME=web_lapig
      # - OAUTH_CLIENT_ID=jupyterhub
      # - OAUTH_CLIENT_SECRET=dkJGtLyC6kvDWlNbEUnlG4wIsn2zTXTH
    networks:
      - web_lapig
    restart: always
    command: >
      jupyterhub -f /srv/jupyterhub/scripts/jupyterhub_config.py
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jupyterhub.service=jupyterhub"
      - "traefik.docker.network=web_lapig"
      - "traefik.http.services.jupyterhub.loadbalancer.server.port=443"
      - "traefik.http.services.jupyterhub.loadbalancer.server.scheme=http"
      - "traefik.http.routers.jupyterhub.rule=Host(`sci.lapig.iesa.ufg.br`)"
      - "traefik.http.routers.jupyterhub.tls.certresolver=le"
      - "traefik.http.routers.jupyterhub.entrypoints=websecure"
    env_file:
      - ../.env

networks:
  web_lapig:
    external: true
    name: web_lapig